export const calendarColumns = [
  { id: "1", header: "Name", className: "min-w-[15rem]" },
  { id: "2", header: "Type", className: "min-w-[8rem]" },
  { id: "3", header: "Calendar", className: "min-w-[8rem]" },
  { id: "4", header: "Category", className: "min-w-[8rem]" },
  { id: "5", header: "Date & Time", className: "min-w-[15rem]" },
  { id: "6", header: "Location", className: "min-w-[10rem]" },
  { id: "7", header: "Actions", className: "min-w-[12rem]" },
];

export const calendarData = [
  {
    eventName: "Tech Conference 2024",
    type: "tech-001",
    calendar: "tech-001",
    category: "tech-001",
    date: "15/06/2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "San Francisco, CA",
  },
  {
    eventName: "Product Launch",
    type: "mkt-002",
    calendar: "mkt-002",
    category: "mkt-002",
    date: "15/06/2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "New York, NY",
  },
  {
    eventName: "Team Building Workshop",
    type: "fin-003",
    calendar: "fin-003",
    category: "fin-003",
    date: "15/06/2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "Austin, TX",
  },
  {
    eventName: "Human Resources",
    type: "hr-004",
    calendar: "hr-004",
    category: "hr-004",
    date: "15/06/2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "Austin, TX",
  },
  {
    eventName: "Operations",
    type: "ops-005",
    calendar: "ops-005",
    category: "ops-005",
    date: "15/06/2025",
    startTime: "09:00",
    endTime: "17:00",
    location: "New York, NY",
  },
];
