"use client";
import React, { useEffect } from "react";
import Label from "../form/Label";
import Input from "../form/input/InputField";
import * as Yup from "yup";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import toast from "react-hot-toast";
import { useParams, useRouter } from "next/navigation";
import Loading from "../atoms/loading/loading";
import { ApiErrorResponse } from "@/services/auth-api/auth-api.types";
import {
  useAddAdvertiserMutation,
  useEditAdvertiserMutation,
  useGetAdvertiserByIdQuery,
} from "@/services/advertiser-api";
import { useLanguage } from "../common/LanguageContext";

const validationSchema = Yup.object().shape({
  companyName: Yup.string().required("Company name is required"),
  nickName: Yup.string().required("Advertiser name is required"),
  registrationNumber: Yup.string().required("Registration number is required"),
  representative: Yup.string().required("Representative is required"),
  businessRegistrationDocument: Yup.string()
    .url("Must be a valid URL")
    .required("Business registration document is required"),
  departmentName: Yup.string().required("Department name is required"),
  bankName: Yup.string().required("Bank name is required"),
});

const EditAdvertiser: React.FC = () => {
  const { t } = useLanguage();
  const router = useRouter();
  const [mutate, { isLoading }] = useEditAdvertiserMutation();
  const { slug } = useParams();
  const { data: advertiserDetail, isLoading: advertiserLoading } =
    useGetAdvertiserByIdQuery(slug, { skip: !slug });
  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
    reset,
  } = useForm({
    resolver: yupResolver(validationSchema),
    defaultValues: {
      companyName: "",
      nickName: "",
      registrationNumber: "",
      representative: "",
      businessRegistrationDocument: "",
      departmentName: "",
      bankName: "",
    },
  });

  const onSubmit = async (formData: any) => {
    try {
      console.log(formData);
      await mutate({ id: slug, ...formData }).unwrap();
      toast.success("Advertiser Updated successfully!");
      router.push("/advertiser-management");
      reset();
    } catch (error) {
      const apiError = error as ApiErrorResponse;
      if (apiError.data && apiError.data.message) {
        toast.error(apiError.data.message);
      } else {
        toast.error("Failed to update advertiser. Please try again");
      }
    }
  };

  const handleLoadAdvertiserData = () => {
    advertiserDetail?.companyName &&
      setValue("companyName", advertiserDetail?.companyName, {
        shouldValidate: true,
      });
    advertiserDetail?.nickName &&
      setValue("nickName", advertiserDetail?.nickName, {
        shouldValidate: true,
      });
    advertiserDetail?.registrationNumber &&
      setValue("registrationNumber", advertiserDetail?.registrationNumber, {
        shouldValidate: true,
      });
    advertiserDetail?.representative &&
      setValue("representative", advertiserDetail?.representative, {
        shouldValidate: true,
      });
    advertiserDetail?.departmentName &&
      setValue("departmentName", advertiserDetail?.departmentName, {
        shouldValidate: true,
      });
    advertiserDetail?.businessRegistrationDocument &&
      setValue(
        "businessRegistrationDocument",
        advertiserDetail?.businessRegistrationDocument,
        {
          shouldValidate: true,
        },
      );
    advertiserDetail?.bankName &&
      setValue("bankName", advertiserDetail?.bankName, {
        shouldValidate: true,
      });
  };

  useEffect(() => {
    if (!advertiserDetail) return;
    handleLoadAdvertiserData();
  }, [advertiserDetail]);

  return (
    <div className="rounded-2xl bg-white dark:bg-white/[0.03] min-h-[calc(100vh-200px)] p-[1.875rem]">
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="pb-4">
            <Label>{t("companyName")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("companyName")}
              error={errors.companyName?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("advertiserName")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("nickName")}
              error={errors.nickName?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("registrationNumber")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("registrationNumber")}
              error={errors.registrationNumber?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("representative")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("representative")}
              error={errors.representative?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("businessRegDoc")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("businessRegistrationDocument")}
              error={errors.businessRegistrationDocument?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("departmentName")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("departmentName")}
              error={errors.departmentName?.message as string}
            />
          </div>
          <div className="pb-4">
            <Label>{t("bankName")}</Label>
            <Input
              placeholder={t("autoGeneratedCampaignName")}
              type="text"
              registration={register("bankName")}
              error={errors.bankName?.message as string}
            />
          </div>
        </div>
        <div className="flex justify-end gap-4">
          {/* <button className="flex items-center justify-center text-white btn-bg h-[2.5rem] w-[10rem] rounded-[5rem]">
          Save
        </button> */}
          <button
            type="submit"
            disabled={isLoading}
            className="flex items-center justify-center  text-[#000] bg-white border border-[#D9D9D9] h-[2.5rem] w-[10rem] rounded-[5rem]"
          >
            {isLoading ? <Loading /> : t("submit")}
          </button>
        </div>
      </form>
    </div>
  );
};

export default EditAdvertiser;
